#!/bin/bash

files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')
if [ -z "$files" ]; then
    exit 0
fi

echo "Running pylint..."
for file in $files; do
    echo "running \`pylint ${file}\` ..."
    output="$(pylint --exit-zero "$file")"

    if echo "$output" | grep -E "[EW][[:digit:]]+:" > /dev/null; then
        echo "detect Error/Warning @ <${file}>:"
        echo "$output"
        exit 1
    fi
done

exit 0
